### ISSUE TITLE
[BUG] Multiplayer extensions saying internet doesn't work when connecting to a game

### ISSUE THREAD

**Issue by roboltz** [Goobwabber/MultiplayerExtensions#131]
Note: I had made this a a bug report before but it was closed because it was a problem with BeatTogether. I had not had BeatTogether installed and just today deleted all of the beattogether files I could find, but MultiplayerExtensions still wouldn't work. (I tested it with and without server browser)

Multiplayer Extensions Version and Download Source
Latest version as of 6/21/2021 and v0.4.7
Your Platform
Oculus Quest hooked up to PC with a Cable. Custom Launch Options: -vrmode oculus

Describe the bug
When trying to join a game with either server browser or through password the game says: "Could not connect to the server. Check your internet connection and try again (CFR-3)" even with good internet.

To Reproduce

Go to 'Online'
Click on 'Join with Code or server browser if mod is installed'
Type code or join a game with same version mod
See error (this is only for me, i don't understand how to make the glitch happen)
Expected behavior
To be able to join a game with code or on server browser.

Log
I don't know what log to show so I will show both logs for beat saber and Multiplayer Extensions:
MultiplayerExtensions Log: 2021.04.09.20.50.36.log (old)
Beat Saber Log: 2021.04.09.20.50.31.log (old)
find the old report for these links to work ^

MultiplayerExtensions Log: 
[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/6689407/_latest.log) (new)
Beat Saber Log: 
[2021.06.21.15.59.38.log](https://github.com/Goobwabber/MultiplayerExtensions/files/6689396/2021.06.21.15.59.38.log) (new)

Screenshots/Video
https://streamable.com/jnhxkx

Additional context
Problem still stays without -vrmode oculus

**Comment by Goobwabber** [comment]
First, just wanna say thanks for following through and opening another issue. A lot of people never open issues for bugs they find and this is a great help. 

Are you still able to create lobbies/join quickplay? Or is this only an issue when you join by code?

**Comment by roboltz** [comment]
I can still join quickplay games and I can create lobbies, but nobody can join them and I can't join others. Also, I can't join server browser games.
