### ISSUE TITLE
[UPDATE] Beatsaber 1.18

### ISSUE THREAD

**Issue by Goobwabber** [Goobwabber/MultiplayerExtensions#136]
1.16.3 breaks the mod hard. To anyone reading, please be patient as I'll likely need to rewrite the core components of the mod.

**Comment by SparkzTehDragon2v** [comment]
Yeah everything died lol. I was hoping this wouldn't happen almost every mod is now down as well which us unfortunate.

**Comment by ErikaEcks** [comment]
any updates? :(

**Comment by deadperch** [comment]
Any chance of this for the weekend?

Thanks for all your efforts here!

**Comment by ErikaEcks** [comment]
Give me your Venmo/Paypal, I will literally p a y you to fix, Father Multiplayer 👀✨

**Comment by deadperch** [comment]
Ditto

**Comment by Anoyomouse** [comment]
I don't like commenting for the sake of commenting, and I know much self-promotion sucks as a programmer, so I'll say this here.

@ErikaEcks and @deadperch There's a sponsor button at the top of the GitHub page here, and links to Ko-fi and Patreon

Unfortunately I can't really assist financially, but I'll be watching this development

**Comment by deadperch** [comment]
> I don't like commenting for the sake of commenting, and I know much self-promotion sucks as a programmer, so I'll say this here.
> 
> @ErikaEcks and @deadperch There's a sponsor button at the top of the GitHub page here, and links to Ko-fi and Patreon
> 
> Unfortunately I can't really assist financially, but I'll be watching this development

Yep, found that, not familiar with the layout of this site and didn't see it initially. Thank you!

**Comment by ErikaEcks** [comment]
It's been 13 years and no update from Zaddy Multiplayer. 🥺🥺🥺

**Comment by Goobwabber** [comment]
Hey, I just wanna say that development is currently paused as I'll be waiting for/assisting BeatTogether with their stuff before working on MultiplayerExtensions. It's likely I'll discontinue support on official servers and it will BT/modded servers only, which is the main reason for the wait. Thanks for being patient!

**Comment by MightiestTaco** [comment]
Dude, we love you, don't worry for a minute about mods taking a while, have a good day :D

**Comment by christofin** [comment]
Any updates on this?

**Comment by Belakor44** [comment]
This mod miss me :(
Is there an another way to play customs songs in multiplayers ?

**Comment by PanGeo-Code** [comment]
> This mod miss me :(
> Is there an another way to play customs songs in multiplayers ?

No as of now not yet but he is woking on it so just give it some more time.

**Comment by marci2oo9** [comment]
will there come an update for 1.17.1 ?

**Comment by Rick278** [comment]
Hopefulliy it will be a update for 1.18.0 and maybe higher at the time.

**Comment by GigaFyde** [comment]
@Rick278 Higher is never a guarantee, but it seems this update should cover 1.17. and 1.18

**Comment by Rick278** [comment]
Yes indeed, I have also seen a branch 0.6.1, but the issue i got with custom songs it says you don't own this song. But there should be progressions somewhere and i hope it will be soon to play together again with my friends.

The only thing i can say for now, thanks for the time you guys are taking for making this mod :D

**Comment by GigaFyde** [comment]
Heh, when I was trying it just said no song selected

**Comment by Rick278** [comment]
yes that's also a message i got with several songs.

**Comment by Kevman95** [comment]
It is because it doesn't work on official servers @Rick278 @GigaFyde cause thats intended. It will only work on our custom servers for BeatTogether. 

This is still in flux. We will release all the MP stuff soon!

**Comment by Rick278** [comment]
> It is because it doesn't work on official servers @Rick278 @GigaFyde cause thats intended. It will only work on our custom servers for BeatTogether.
> 
> This is still in flux. We will release all the MP stuff soon!

Ok thank you for this info. I think a lot off people will be gratefull after the release :D It's been a long time people could play custom songs together.

**Comment by marci2oo9** [comment]
will there come an update for 1.18.2 ?

**Comment by ry60003333** [comment]
Is there any way we can help with the progress for 1.18.x compatibility? Like maybe a bounty or something to compensate you for the amazing work you've done? 💰👀

**Comment by SamJonesUniversity** [comment]
If you really want to play multiplayer with friends you can just downgrade to 1.16.2 following this guide: https://steamcommunity.com/sharedfiles/filedetails/?id=1805934840

Make sure to delete all mods and clear them in your user data too. Then dload beat together and multiplayer extensions from mod assistant and you can play. Tested with my friend yesterday and works fine. Note you have to run a beat together server as official will not work.

**Comment by Kevman95** [comment]
If your downgrading, just use the BT plugin to play. It still works on older copies till update.
