### ISSUE TITLE
[BUG] Black Screen whenever starting game

### ISSUE THREAD

**Issue by furik90** [Goobwabber/MultiplayerExtensions#140]
**Multiplayer Extensions Version and Download Source**
0.5.4 via GitHub

**Your Platform**
Oculus Rift cv1

**Describe the bug**
Whenever I load the game up after the file being installed in the correct place I select continue to main menu but the game stays in a black screen and doesn't load.

**To Reproduce**
1. Install file
2. Launch game
3. Press continue
4. black screen

**Expected behavior**
I expected the game to load as it normally would before I had installed the mod

**Log**
[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/6912104/_latest.log)

**Comment by AhegaHOE** [comment]
Please read the #136 the update broke the mod just dont use it, i've got the same problem and without it the game works totally fine. just be patient for the update they're putting all their efforts up to fix this.

**Comment by lockup62** [comment]
Same here. I hope this issue is fixed.
