### ISSUE TITLE
[BUG] My MultiplayerExtensions isn't loading.

### ISSUE THREAD

**Issue by Cozax** [Goobwabber/MultiplayerExtensions#142]
**Multiplayer Extensions Version and Download Source**
MultiplayerExtensions v0.5.4 - Downloaded from the github releases

**Your Platform**
I'm on PC using the Steam version of Beat Saber [Version 1.16.4] and my headset is an oculus rift S. The only launch option I have is `--verbose`.

**Describe the bug**
My MultiplayerExtensions isn't loading correctly, it seems I don't have access to any of it features in game. I did checked the logs as said in the README.md, and it looks like my BeatSaverSharp is missing.
`[WARNING @ 21:51:13 | IPA/Loader] 'MultiplayerExtensions' is missing depencency 'BeatSaverSharp@^2.0.1'; ignoring`
However, BeatSaverSharp is installed correctly through ModAssistant and detected as well by the game.

Maybe it is because I have BeatSaverSharp@^3.0.1 instead of @^2.0.1

**Log**
[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/6995559/_latest.log) [Error line 93]

**Screenshots/Video**
`ModAssistant -> BeatSaverSharp`
![image](https://user-images.githubusercontent.com/29103374/129632757-a37d7a23-8db3-4843-92c5-ceaf41d30ea2.png)

`Beat saber console (--verbose) -> BeatSaverSharp is detected by the game and loaded correctly`
![image](https://user-images.githubusercontent.com/29103374/129632869-8ccf57a5-d3d0-46f3-93dc-dafe8306df8a.png)

**Comment by Weaszle** [comment]
Version 1.16.3 / 1.16.4  is not supported.

1.16.4 is not supported 

https://github.com/Goobwabber/MultiplayerExtensions/issues/136

**Comment by Cozax** [comment]
> Version 1.16.3 / 1.16.4 is not supported.
> 
> #136

My bad, thanks for your reply
