### ISSUE TITLE
[BUG] BEAT SABER 1.17.0 Support

### ISSUE THREAD

**Issue by Scorezy** [Goobwabber/MultiplayerExtensions#144]
Hello Dear creator of this mod

I have a problem I would like to use this mod for myself and my friend but unfortunately the shit is so bad that in online mode no Customs songs are only 2% you are there and then you are gone I would like to include custom songs friends play we need an update or an alternative!

**Comment by MrMagoffin** [comment]
Could you be any more entitled? The 1.16.3 update changed fundamentally how multiplayer works which will require a fair bit of effort to overcome. Modders do all this work essentially for free. Have patience, or better yet find another community.

**Comment by RexNotRex** [comment]
Goobwabber will update MultiplayerExtensions when they have time, in the meantime, we just have to wait.

**Comment by SilberComic** [comment]
its not updated for 1.17.0 so either downgrade or wait or update it yourself no need to be angry about the dev

**Comment by Goobwabber** [comment]
its being worked on
