### ISSUE TITLE
[BUG] Cant play custom songs

### ISSUE THREAD

**Issue by PanGeo-Code** [Goobwabber/MultiplayerExtensions#146]
**Multiplayer Extensions Version and Download Source**

**Your Platform**

**Describe the bug**
Cant press play when i have a song selected in a multiplayer lobby.

**To Reproduce**
1. Go to 'Multiplayer create an official server'
2. Click on 'select song'
3. choose a custom song 'select the song'
4. See that u cant click play

**Expected behavior**
Me being able to press olay and play custom songs with friends.

**Log**
https://hastebin.geobizzarcraft.eu/dogerozado.yaml

**Screenshots/Video**
![unable to play custom songPNG](https://user-images.githubusercontent.com/81773780/133002996-04da1769-d78d-4eab-8791-e67800eac163.PNG) 

**Additional context**
 I compiled it 1 hour ago from posting this.

**Comment by qe201020335** [comment]
Actually, if you select an ost song first, then select a custom song, it will work.

**Comment by PanGeo-Code** [comment]
> Actually, if you select an ost song first, then select a custom song, it will work.

What do you mean with ost?

**Comment by qe201020335** [comment]
The songs that come with the game.
for example
Select $100 Bill from OST1 (any difficulty) first, then select a custom song.

**Comment by PanGeo-Code** [comment]
ah yes i see that does work.

But ill leave my issue open because its still an bug

**Comment by DarkObscurity** [comment]
> The songs that come with the game.
> for example
> Select $100 Bill from OST1 (any difficulty) first, then select a custom song.

doesn't work in multiplayer, it just plays the original selected song.

**Comment by PanGeo-Code** [comment]
> > The songs that come with the game.
> > for example
> > Select $100 Bill from OST1 (any difficulty) first, then select a custom song.
> 
> doesn't work in multiplayer, it just plays the original selected song.

I can confirm

**Comment by qe201020335** [comment]
@PanGeo-Code I think today's commits broke it. I just built a new version with today's commits and it no longer works.

**Comment by Goobwabber** [comment]
I ended up deleting all code related to making it work on official servers because it wasn't worth how buggy things would be. BeatTogether's dedicated servers are currently in testing phase and the new commits are made to work with those servers instead. Since the mod hasn't been publicly released I'm closing this issue.
