### ISSUE TITLE
[BUG] Doesn't Like BeatSaverSharp v3.0.2

### ISSUE THREAD

**Issue by Seqan01** [Goobwabber/MultiplayerExtensions#149]
Hi! Just downloaded today to try it out. After perusing through, I understand the mod is not currently ready because of Beat Together, but I thought this might be worth mentioning.

Downloaded straight from Git for PC on Index. No custom button in the multiplayer menu. Went into the log to see what happened, and Beat Saber thinks I don't have BeatSaverSharp. I did, version 3.0.2. My guess is maybe there's an internal flag that isn't okay with BeatSaverSharp v3.0.0+? 3.0.2 is what's in ModAssistant right now.

Thanks for the work that's been done on this. I apologize if this is a known thing and I missed it on my reading of the Git.

**Comment by Piotrekol** [comment]
As you mentioned, this mod currently doesn't work with BS 1.18. However, it seems to be fixed in #137

https://github.com/Goobwabber/MultiplayerExtensions/blob/3b6420a4f4206fabcae20282baf1b6fea73e57db/MultiplayerExtensions/manifest.json#L12
