### ISSUE TITLE
Walls get's stuck at Score Screen.

### ISSUE THREAD

**Issue by LedgendODST** [Goobwabber/MultiplayerExtensions#15]
Hello, 

i want to report a bug me and my friend was playing a map (while in the lasts seconds comes a wall and sticks to it) my friend also had the problem, but the wall was gone when we was in the main lobby again.

Picture
https://prnt.sc/v90jfe

**Comment by Zingabopp** [comment]
I'm pretty sure this isn't really a bug with MultiplayerExtensions. I would guess that it's a bug with the base game because they don't have any songs that have walls showing when the song ends.

**Comment by LedgendODST** [comment]
maybe you find a way to fix it maybe hehe
