### ISSUE TITLE
[BUG] automatic download doesn't work

### ISSUE THREAD

**Issue by LosWheatleynDew** [Goobwabber/MultiplayerExtensions#154]
**Multiplayer Extensions Version and Download Source**
v0.5.4 mod assistant
**Your Platform**

PC Using Oculus Link, Steam store
**Describe the bug**

When a user picks a song that the other doesn't have. It shows up blank 
Even when the game tries to start it goes for an infinite loading loop
However with both of us has the song downloaded it works fine.
**To Reproduce**

1. go to mulitplayer
2. choose beat together and create a lobby
3. You or someone chooses a song that you don't have
4. Blank thumbnail. Cannot start or infinite loading

**Expected behavior**

Since the player doesn't  have the song It expected to download the song and allowed the game to be played
**Log**

[2021.11.04.15.38.52.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7491414/2021.11.04.15.38.52.log)

Using beatsaber v1.16.2
Latest version of BeatTogether v1.1.3

**Comment by varanova** [comment]
The current version no longer supports downloads (due to an API change on beat saver.)
There's a patch I found from a member on the beat saber mod discord that patches this.

(https://drive.google.com/file/d/1td1uOuSJSj_hM2CJwnRPq1lRpZjliDMP/view)

I didn't create it, though it does fix downloading. I'd give credit to whoever DID patch it, but I honestly don't know.

**Comment by LosWheatleynDew** [comment]
The new mod you gave works now
thanks

**Comment by LosWheatleynDew** [comment]
> The current version no longer supports downloads (due to an API change on beat saver.) There's a patch I found from a member on the beat saber mod discord that patches this.
> 
> (https://drive.google.com/file/d/1td1uOuSJSj_hM2CJwnRPq1lRpZjliDMP/view)
> 
> I didn't create it, though it does fix downloading. I'd give credit to whoever DID patch it, but I honestly don't know. (Also, only works on 1.16.2, but you already said you're on that version.)

Welll...
[2021.11.07.16.13.53.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7493462/2021.11.07.16.13.53.log)
.
the new songs does work but now beatsaver is throwwing off errors and some errors as well
at this point i have no idea what is the cause of this because i tried reinstalling and clearning all files
