### ISSUE TITLE
[BUG] Host cannot start session

### ISSUE THREAD

**Issue by GhostFancy** [Goobwabber/MultiplayerExtensions#156]
**Multiplayer Extensions Version and Download Source**
v0.6.2 from Github

**Your Platform**
PC, Oculus Rift S

**Describe the bug**
When myself and another player join a lobby and select the same song, the client player can ready up, but the host cannot start the match

**To Reproduce**
1. Host and Player have exact same song downloaded
2. Host a session and let player join session
3. Have host and player pick same song
4. Client player can ready up, but host cannot start

**Expected behavior**
Host should be able to start the session/match/level

**Log**
[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7549339/_latest.log)

**Comment by IonEwe** [comment]
i have this same issue.... quest 1 + link, 1.18.1. Blocks both standard in game multi and custom. 
noticed that on the server mod multiplayer settings menu that there was an error for "stats" and the easter egg could not be turned off.

**Comment by W3zel** [comment]
I figured it out I think, I'm on PC and if you want to host a game with custom songs start it up through Beat Together, 
![unknown-436](https://user-images.githubusercontent.com/73921659/142089328-10461cb0-c3b7-454b-9c7d-482a09514f20.png)
Like this, you can enable the lobby to be viewable through server browser in the in game settings.

**Comment by Firestorm7893** [comment]
Got a similar problem. I cannot start the lobby, most of the time I get a connection error (cfr-3). When I'm able to create the server when my friend joins cannot use custom songs, even tough both of us have multiplayer extensions and beattogheter installed

**Comment by Belakor44** [comment]
I install the mod + beattogether and i haven't the "server browser" button like the screenshot :(
I'm alone ?

**Comment by Firestorm7893** [comment]
> I install the mod + beattogether and i haven't the "server browser" button like the screenshot :( I'm alone ?

You need to install the server browser mod for it to appear. It's separate from M Extensions

**Comment by Belakor44** [comment]
> > I install the mod + beattogether and i haven't the "server browser" button like the screenshot :( I'm alone ?
> 
> You need to install the server browser mod for it to appear. It's separate from M Extensions

Thank you ;)
