### ISSUE TITLE
I installed the multiplayer extension and it shows custom songs but i select the song in private match and says song not selected would any one know the fix  

### ISSUE THREAD

**Issue by blazencreed** [Goobwabber/MultiplayerExtensions#160]

**Comment by Flxma** [comment]
Same problem here

**Comment by TheInevitableLuke** [comment]
Same problem, no fix, but I checked the _latest.log file and found this:
`[WARNING @ 17:23:05 | IPA/Loader] 'MultiplayerExtensions' is missing dependency 'SiraUtil@^2.5.2'; ignoring`

I have SiraUtil 3.0.2 installed, so my guess is that this needs to be updated to use the newest version.

**Comment by MasterChef5311** [comment]
> Same problem, no fix, but I checked the _latest.log file and found this: `[WARNING @ 17:23:05 | IPA/Loader] 'MultiplayerExtensions' is missing dependency 'SiraUtil@^2.5.2'; ignoring`
> 
> I have SiraUtil 3.0.2 installed, so my guess is that this needs to be updated to use the newest version.

yeah i have the same issue, i also think it would make sense that the version that MultiplayerExtensions is using is out of date?

**Comment by joshuasuperboy** [comment]
> _No description provided._

1. First launch beatsaber then close the game. 
2. Now go into the beatsaber game folder and in there you should see a folder called logs.
3. So open that folder by double left clicking it. 
4. Then in that logs folder you just opened, you should see a list of files in there. The file you will want to send is the file that is named "_latest.log". 

So send that here after opening your game then closing it.
