### ISSUE TITLE
[BUG] Custom song bar/list not showing up

### ISSUE THREAD

**Issue by MasterChef5311** [Goobwabber/MultiplayerExtensions#163]
Steam

download the extension, launch game, open private lobby, don't see custom song bar/button or anything new.
tried favoriting custom songs, the show up but when i select them i cannot play it just says song not selected when i hover over play button says no song selected

put the MultiplayerExtensions.dll into the plugins folder and launch
Log says its missing sirautil version 2.5.2 but i download it from mod assistant, but in the game files it shows sirautil in plugins
only thing i can think is i have sirautil 3.0.2 from mod assistant and maybe this extension requires a older version of sirautil?

[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7786161/_latest.log)

![image](https://user-images.githubusercontent.com/56269722/147602191-dcece2f0-04ff-4cc3-8eb9-677cce39fb73.png)

![image](https://user-images.githubusercontent.com/56269722/147602258-6bcd2ebf-59bf-40a3-a993-8342f87c4d9d.png)

**Comment by chrisericvitch** [comment]
hello got the same problem it says no multiplayer extensions active and so i cant play with custom songs - seems to be a problem with 1.19 update of the game ? i tried to erase and re - install the game but got the same problem . 
playing on my pc with an occulus rift s .

**Comment by Waffelparty** [comment]
the actual build of Multiplayer Extensions is for 1.18. We need to wait for an update for 1.19
