### ISSUE TITLE
cant play custom songs since 1.19 update of beat saber [BUG] 

### ISSUE THREAD

**Issue by chrisericvitch** [Goobwabber/MultiplayerExtensions#164]
**MultiplayerExtensions-v0.6.2  **

**pc + occulus rift s  - playing from occulus store **

**cant play custom songs since 1.19 update **

**To Reproduce**

**Expected behavior**

**Log**

**Screenshots/Video**

![bug multiplayer beat saber](https://user-images.githubusercontent.com/96820809/147659459-6948c590-6026-4c5f-906d-4d3ab8259edf.jpg)

**Additional context**

**Comment by Monk2052** [comment]
same problem here are you on 1.19.0?

**Comment by Monk2052** [comment]
cause its ony updated to 1.18.0

**Comment by chrisericvitch** [comment]
yes on 1.19 - when will we get update ?

**Comment by blackfisch** [comment]
https://github.com/Goobwabber/MultiplayerExtensions/issues/170#issuecomment-1015503393 maybe this clears some things up for you guys
