### ISSUE TITLE
[BUG] BeatTogether Cannot Create a Server

### ISSUE THREAD

**Issue by big-dumpling** [Goobwabber/MultiplayerExtensions#170]
**Multiplayer Extensions Version and Download Source**
v0.6.2 installed manually

**Your Platform**
PC

**Describe the bug**
Tried to create a server with BeatTogether but it says

**To Reproduce**
1. Click *online* on title screen
2. Scroll to *BeatTogether* server type
3. Click on *create server*
4. Click on *create* after choosing player limit
5. After it's connecting for a few seconds, it says "Could not connect to the server. Check your internet connection and try again (CFR-9)

**Expected behavior**
It should create a server just like the official servers

**Log**
[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7850585/_latest.log)

**Comment by big-dumpling** [comment]
Upon further inspection I realised I had a version (3.0.3 of SiraUtil) but it said it needed v2.5.2

**Comment by Monk2052** [comment]
does it work on 1.19.0?

**Comment by joshuasuperboy** [comment]
> does it work on 1.19.0?

No it does not work on 1.19.0.

**Comment by joshuasuperboy** [comment]
> **Multiplayer Extensions Version and Download Source** v0.6.2 installed manually
> 
> **Your Platform** PC
> 
> **Describe the bug** Tried to create a server with BeatTogether but it says
> 
> **To Reproduce**
> 
> 1. Click _online_ on title screen
> 2. Scroll to _BeatTogether_ server type
> 3. Click on _create server_
> 4. Click on _create_ after choosing player limit
> 5. After it's connecting for a few seconds, it says "Could not connect to the server. Check your internet connection and try again (CFR-9)
> 
> **Expected behavior** It should create a server just like the official servers
> 
> **Log** [_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7850585/_latest.log)

You are using version 1.19.0 of beatsaber which is the version of beatsaber that this mod does not work on just yet.

**Comment by yusuf576** [comment]
> No it does not work on 1.19.0.

how do you play it then?

**Comment by blackfisch** [comment]
> > No it does not work on 1.19.0.
> 
> how do you play it then?

at the moment - not at all or downgrade your game (there's guides on the internet but the setup is ridicolous if you ask me)

some people already tried fixing it (including me) without success. I even suspect the game devs actually broke compatibility and this might need a custom solution to work properly in the future

**Comment by texic88** [comment]
just for everyone waiting till the update comes. there is an easy way to downgrade with BSlegacy. all my friends use it too
https://bslegacy.com/
