### ISSUE TITLE
[FEATURE] Update to latest version

### ISSUE THREAD

**Issue by SirGamers** [Goobwabber/MultiplayerExtensions#177]
**Is your feature request related to a problem? Please describe.**
Yes. Latest version won’t work on latest version of beat saber

**Describe the solution you'd like**
Update to work with the latest version of beat saber

**Comment by mryabets** [comment]
Just in case anyone's looking, there is a working fork for 1.37-1.38.
https://github.com/EnderdracheLP/MultiplayerExtensions/tree/dev/1.37
And here is the built plugin for 1.38: [link](https://1drv.ms/u/c/7044f948628d7ab1/EcqaG3-rZF1Pm7AuhbvFen0BhJMvIyFE4BwQJrSalL7SJQ?e=okA8kw)
