### ISSUE TITLE
[BUG] When failing to join a lobby the solo menu will bug out

### ISSUE THREAD

**Issue by ItsCharaHere** [Goobwabber/MultiplayerExtensions#61]
**Your Platform**
PC

**Describe the bug**
When failing to join a multiplayer lobby (tested with server browser) the Solo song scene's hud is stuck on the ceiling, the solo menu's modifiers tab will be the mods tab from the main menu, the song select will tell you when a song is not able to be downloaded from beatsaver, and attempting to join any more games fails (possibly server browser bugging out though, will need more testing) see: https://github.com/roydejong/BeatSaberServerBrowser/issues/20

**To Reproduce**
Go into server browser or join by code,
Join Game from code or server browser and fail to join

**Expected behavior**
Menus and In-Song Scene should behave as normally

**Log**
See Issue linked

**Screenshots/Video**
See Issue linked

**Additional context**

**Comment by Goobwabber** [comment]
Fairly sure this is an issue with bsml's gameplay-setup menu in multiplayer. In the future, mpex is moving from there to the center view, so it won't be an issue then.
