### ISSUE TITLE
[Feature] Stop Insta-Fail with SteamVR Overlay

### ISSUE THREAD

**Issue by christofin** [Goobwabber/MultiplayerExtensions#62]
**Your Platform**

PC

**Describe the bug**
Accessing the SteamVR overlay during a song with the multiplayer extensions mod causes the user to fail the song instantly, even if they wouldn't have otherwise failed. 

**To Reproduce**
Launch multiplayer, 2 or more players, play song, have either player pull up the overlay (by hitting the home button on the controller). Instant fail.  

Happens on the latest build from 12 days ago for both my friend with a Vive and me with an Index. 

Launch song in multiplayer with 2 or more players, pull up SteamVR overlay in the middle of the song, instant fail. 

**Expected behavior**
The SteamVR overlay to not cause the song to fail.

**Comment by Zingabopp** [comment]
Have you tried this without MultiplayerExtensions? It seems like something the base game might do.

**Comment by christofin** [comment]
I did just test this with MultiplayerExtensions removed and it looks like this is an issue with the base game, so I'll report this to the Beat Saber team. In single player the game is paused, but in multiplayer the overlay causes an instant fail. 

Thanks for the response. One more question, not related, but just curious - do you plan on submitting Multiplayer Extensions to be reviewed for Mod Assistant? Would be great to have this amazing mod integrated directly with Mod Assistant!

**Comment by Zingabopp** [comment]
It might be intentional since you can't pause during Multiplayer, we might be able to add not insta-failing as a feature. We have some more work to do before it's ready for Mod Assistant.
