### ISSUE TITLE
[BUG] Solo Score Screen and Party Post-Song Name Entry Keyboard/Score Screens Not Showing

### ISSUE THREAD

**Issue by AlphaTwister** [Goobwabber/MultiplayerExtensions#64]
Platform:
PC/Steam on HTC Vive, Beat Saber version 1.13.0 with ModAssistant Version 1.1.16

The Bug:
After installing the custom song multiplayer mod and having a blast online with friends (truly, well done to all in this effort, I'm amazed at how "Plug and Play" it is), I found my Solo score screen and Party Post-Song Name Entry Keyboard/Score Screens no longer show after finishing a song. Scores in Solo DO update to the online leaderboards, but we obtain no notice of how we did or our ranking until back in the song select. An audible "loading buffer" is heard but this is normal (associated with having mods installed, sounds like a "Dadadada" for a quarter- to half-a-second). It is worth noting the score screen IN multiplayer is unaffected. This issue appears to be as if something is kicking the game past the post-song score screens like we do in multiplayer where we return to the lobby and not to a separate window for the round's results.

To Reproduce:
1) Install the multiplayer custom song mod.
2) (May not be relevant) - Play several songs online with your friends. It is worth noting I did end up downloading a song automatically from Beat Saver as I did not have it in my library (perhaps a cause?). Game continued to work fine.
3) (Also may not be relevant) - Attempted to play a song only one of us had locally (custom made song amongst my friends) and their instance was stuck "Waiting for Other Players." I could not cancel the loading of their song and had to restart the server to release them of their purgatory (another potential cause?). Game continued to work fine in multiplayer until finished.
4) Play a custom song in Solo mode.
5) Observe the lack of a post-song score screen.
6) Check if the issue persists in Party mode. Confirm this is the case.

Expected Behavior: 
After a song is finished the game should pull up a post-song score screen and/or keyboard to enter a name in Party mode. Neither occur now, and Party song scores can no longer be saved. 

Log:
See below.
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5676922/_latest.log)

Screenshots/Video:
None available unfortunately.

Additional context:
Other mods I have installed in case of conflict:
1) BSIPA - 4.1.3
2) SongCore - 3.0.3
3) BeatSaverVoting - 1.3.2
4) CameraPlus - 4.4.2
5) ScoreSaber - 2.3.6
6) BeatSaverDownloader - 5.3.3
7) Mapping Extensions - 1.5.0
8) SiraUtil - 2.2.0
9) BeatSaberMarkupLanguage - 1.4.2
10) BS Utils - 1.6.5
11) Noodle Extensions - 1.3.4
12) CustomJSONData - 1.1.2
13) SongDataCore - 1.3.5
14) ScoreSaberSharp - 0.1.0
15) BeatSaverSharp - 1.6.0 -------------------------------------------------------> This mod never shows as installed in my mod list but every mod has worked without issue. It shows as "installed" (green numbers in the "Installed" column) after a updating/installing, but never when reopening ModAssistant. Potential issue?
16) Ini Parser - 2.5.7
17) Technicolor - 1.0.2
18) Chroma - 2.2.8
19) SongBrowser - 6.1.2

**Comment by Goobwabber** [comment]
This is likely another issue with the Gameplay Setup Menu UI errors, which should hopefully be fixed in 0.4.0 upon release.

**Comment by AlphaTwister** [comment]
Fantastic, thanks for the heads up. I'll confirm if that's the case upon the release of 0.4.0.

**Comment by joeycf** [comment]
To add to this. I was testing the MultiplayerExtensions and just went to host a lobby (with nobody to join) and I checked to see if I could play a custom song, I saw them as an option so I left (without ever trying to play a game) and went to party mode (my mode of choice due to having multiple players in the household who want to have scores) and I was also unable to get the name entry / score screen to show up even when I was sure to have a score in the top 10.
