### ISSUE TITLE
[BUG] Never Loads in on Custom/Vanilla Song *Updated for 0.4.0*

### ISSUE THREAD

**Issue by Zelrion** [Goobwabber/MultiplayerExtensions#69]
**Your Platform**
PC/Steam w/HTC Vive
PC/Steam w/Rift S

**Describe the bug**
The game stalls out in "Waiting for Players" screen, my friend gets stuck in lobby. Doesn't matter who is host or the song,
including vanilla songs.
Possibly being caused by null reference exception?

**To Reproduce**
Both players ready up for a song, doesn't appear to matter if both players have the song or not.
Upon finishing the countdown, bug will occur.

**Log**
Trimmed down to relevant section. Still errors out on 0.4.0.
...
[DEBUG @ 18:14:47 | MultiplayerExtensions] Joining a None lobby.
[DEBUG @ 18:14:48 | MultiplayerExtensions] Joining a PartyHost lobby.
[INFO @ 18:14:59 | MultiplayerExtensions] Player 'bExc5y4HIsYGry51P62Hes' joined
[DEBUG @ 18:14:59 | MultiplayerExtensions] (PacketSerializer) Received 'MultiplayerExtensions.Sessions.ExtendedPlayerPacket'
[INFO @ 18:14:59 | MultiplayerExtensions] Received 'ExtendedPlayerPacket' from 'bExc5y4HIsYGry51P62Hes' with '76561198311920617'
[DEBUG @ 18:15:04 | MultiplayerExtensions] CustomLevels are enabled.
[DEBUG @ 18:15:08 | MultiplayerExtensions] PreviewBeatmap(100Bills): Loaded from local.
[WARNING @ 18:15:08 | MultiplayerExtensions] Beatmap with level ID '100Bills' cannot be converted to a valid Beat Saver hash.
[CRITICAL @ 18:15:08 | UnityEngine] NullReferenceException
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.RectTransform.get_sizeDelta () (at <97fdf0a75ab94da9a7e5188c186e574d>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.HorizontalOrVerticalLayoutGroup.GetChildSizes (UnityEngine.RectTransform child, System.Int32 axis, System.Boolean controlSize, System.Boolean childForceExpand, System.Single& min, System.Single& preferred, System.Single& flexible) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis (System.Int32 axis, System.Boolean isVertical) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.HorizontalLayoutGroup.SetLayoutHorizontal () (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder+<>c.<Rebuild>b__12_1 (UnityEngine.Component e) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.Rebuild (UnityEngine.UI.CanvasUpdate executing) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.Canvas:SendWillRenderCanvases()
[CRITICAL @ 18:15:08 | UnityEngine] NullReferenceException
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.RectTransform.get_sizeDelta () (at <97fdf0a75ab94da9a7e5188c186e574d>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.HorizontalOrVerticalLayoutGroup.GetChildSizes (UnityEngine.RectTransform child, System.Int32 axis, System.Boolean controlSize, System.Boolean childForceExpand, System.Single& min, System.Single& preferred, System.Single& flexible) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis (System.Int32 axis, System.Boolean isVertical) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.HorizontalLayoutGroup.SetLayoutHorizontal () (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder+<>c.<Rebuild>b__12_1 (UnityEngine.Component e) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.PerformLayoutControl (UnityEngine.RectTransform rect, UnityEngine.Events.UnityAction`1[T0] action) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.LayoutRebuilder.Rebuild (UnityEngine.UI.CanvasUpdate executing) (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at <59d11edce11547ceaeb7d303c9f1e55c>:0)
[CRITICAL @ 18:15:08 | UnityEngine] UnityEngine.Canvas:SendWillRenderCanvases()
[DEBUG @ 18:15:09 | MultiplayerExtensions] Level with ID '100Bills' already exists.
[DEBUG @ 18:15:10 | MultiplayerExtensions] PreviewBeatmap(100Bills): Cached preview found, skipping beatsaver request.
[DEBUG @ 18:15:15 | MultiplayerExtensions] PreviewBeatmap(100Bills): Cached preview found, skipping beatsaver request.
[DEBUG @ 18:15:15 | BS_Utils] Level Data set
[DEBUG @ 18:15:17 | SiraUtil] Installing: SiraSaberInstaller (SiraUtil)
[DEBUG @ 18:15:33 | SiraUtil] Installing: SiraMultiGameInstaller (SiraUtil)
[DEBUG @ 18:15:33 | SiraUtil] Installing: XGameInstaller (Enhancements)
[INFO @ 18:16:09 | MultiplayerExtensions] Player 'bExc5y4HIsYGry51P62Hes' disconnected
...

**Additional context**
Not sure if relevant to https://github.com/Zingabopp/MultiplayerExtensions/issues/67
Possibly related to https://github.com/Zingabopp/MultiplayerExtensions/issues/23

**Comment by KnuffelBeestje** [comment]
Same issue here

**Comment by leobacher** [comment]
same

**Comment by mentalityrl** [comment]
Experiencing this issue too.

**Comment by Gamegod4** [comment]
This has been an issue that's in the mod for a while. There needs to be some way of telling if people have the song or are still downloading it. In the old 1.11 version, you could tell who had the song and how long it would take to download. Now in this version you can't tell and have to take a chance, because if they don't have it your odds of full crashing are basically 100%. It has been much smoother when they do have the song, but this loading issue can still happen

**Comment by Nyx-WildSiren** [comment]
We are also having this issue, we have a lobby of 5 players, and there are some definite issues for us. Host selects a custom song, and for those of us that do not have it, Beat Saber shows us a random song from our library. Same thing happens if someone else selects a song and so forth. Doesn't matter who is hosting, it's continuous across our group of 5.

**Comment by Zingabopp** [comment]
The UI layout errors shouldn't affect anything, that's actually a BSML bug when Gameplay Options tabs are added (somehow a layout element is getting destroyed, but not removed from the list of layout elements Unity's UI accesses). Custom song downloading might be fixed with #73, BeatSaver was changed to block generic UserAgents from BeatSaverSharp.

**Comment by Logan346** [comment]
Same issue, i've got the Oculus quest 1 and trying to play with a mate with a Vive, either get stuck in lobby or "waiting for players" screen.

**Comment by QwrtyMan** [comment]
This same issues is occurring for me as well -- i even tried downloading the latest build under Artifacts, and still no luck.
Is there any fix?

**Comment by DMaskR** [comment]
Same issue, used to work with two other friends but now I get stuck on "Waiting for Other Players" and he just crashes.

**Comment by kunjaf14** [comment]
I'm experiencing the same thing on a Rift-S. Until December I had no issues with up to 3 people in a lobby. My custom songs work in solo play, but any time I try them in multiplayer we get stuck right after the countdown ends. We tried songs that we know worked before, but no luck.

**Comment by TrisXD** [comment]
I have this bug at the moment too, the spectate feature allows me to watch my friend play custom songs but not participate.
