### ISSUE TITLE
[FEATURE] Re-join on fail

### ISSUE THREAD

**Issue by harry1453** [Goobwabber/MultiplayerExtensions#72]
**Is your feature request related to a problem? Please describe.**

It would be nice if players who fail could join in again, and if this could be enabled/disabled for the lobby.

**Describe the solution you'd like**

Allow players who've failed to join back in with their score reset, like the old mod did.

**Additional context**

**Comment by stanfear** [comment]
From what I have seen, the new NoFail modifier works perfectly for that. (no penalties if no failed, but score/2 once failed)

I believe that modifier is enabled in public lobbies, but enabling it in custom maps sounds like a good alternative to a rejoin function that would need work to be put in

**Comment by harry1453** [comment]
It works but I prefer the old way where you can rejoin to try again but your score is reset to 0..

**Comment by aceadamuk** [comment]
i hope they can work this feature into it. it sucks failing then just standing there for 2 mins doing nothing....
