### ISSUE TITLE
NoodleExtensions/MappingExtensions support

### ISSUE THREAD

**Issue by Goobwabber** [Goobwabber/MultiplayerExtensions#96]
At the moment NE and ME work in multiplayer, but they should be disabled when a player is missing a requirement. 
NE maps might just need to be disabled, noodle does too many fancy things lmao

**Comment by aceadamuk** [comment]
i think with people getting custom songs will just end up getting ME and NE anyway as allot of cool maps use them.

**Comment by Goobwabber** [comment]
That doesn't mean that some limitation shouldn't be put in place if a user doesn't have either of them though.

**Comment by Goobwabber** [comment]
Both MappingExtensions and NoodleExtensions now work in multi, so closing.
