### ISSUE TITLE
[BUG] Black screen when joining a lobby - still have haptics

### ISSUE THREAD

**Issue by amazekiwi01** [Goobwabber/MultiplayerExtensions#97]
**Your Platform**
Rift S on Steam oculus mode

**Describe the bug**
When joining a lobby the loading screen (Joining X's game (XXXXX)) ends faster than typical and instead of loading into a lobby waiting area or grandstand it just stays black, if I move my controller I get haptics as if I was loaded in but had my eyes closed. Only way to leave this state is to reboot the game but the issue will persist with any lobby I join, I've found that for some reason I can get it to behave normally again by playing a single map in Solo Play.

**To Reproduce**
Not sure what it's caused by, but it most often occurs when a lobby has chosen a song and it fails to load everyone in properly (lobby of five somehow becomes 1 person in the layout for a single person lobby and/or multiple people fail instantly).

**Expected behavior**
Expect to join a lobby as normal.

**Log**
Log unvailable

**Additional context**

**Comment by moshier1** [comment]
same thing happens to me

**Comment by B-u-r-a-G** [comment]
same issue here

**Comment by VikingAl** [comment]
same thing here

**Comment by A-plou** [comment]
that bug actually fix itself at some point if you move a little bit and wait a little bit. 
I don't really know what cause that problem, I believe it's because of where you place like if you are sitting or crouching or out of the platform of the multiplayer platform it can cause that problem or some other.
